### ISSUE TITLE
Reloading resources without altv-server connection - esbuild

### ISSUE THREAD

**Issue by Ymaril** [xxshady/altv-esbuild#22]
I wanted to deploy altv-server for local development in Docker. And I'm having trouble net connecting altv-server-inject to my esbuild server.

The problem would be solved by being able to specify the host of the esbuild server.

But I thought, why is this connection needed at all? Altv server itself can monitor resource updates and reload them on the fly.

I tested fs.watch too

```js
import fs from "fs";

fs.watch('./resources/chat/server/index.js', (eventType, filename) => {
  alt.log(filename + ' changed');
});
```
And it works.

You can tie a resource reloading to this.

This can even be packaged as a separate resource for reloading resources. And use it in esbuild

**Comment by xxshady** [comment]
> But I thought, why is this connection needed at all?

in [previous iteration](https://github.com/xxshady/esbuild-plugin-altv-dev-server/blob/3a6c5983452412852065fa397db0799374753082/src/alt-overwrite-banner.js#L270) of this esbuild plugin i exactly used `fs.watch` but it did not work well so in current iteration esbuild callbacks [are used](https://github.com/xxshady/altv-esbuild/blob/fa6196e40df74461f9b6e9d476f2361bd4c50b72/src/plugin/server/setup.ts#L117)

i can add `hotReloadServerHost` option similar to `hotReloadServerPort`
