### ISSUE TITLE
Add playerDisconnect emit on resource restart

### ISSUE THREAD

**Issue by stanislawkrowicki** [xxshady/altv-esbuild#8]
Players reconnect emulation emits playerConnect, so why not emit playerDisconnect as well?

**Comment by xxshady** [comment]
playerDisconnect event listener in many gamemodes will probably contain async code (database stuff), and by default altv js module will not wait to async listeners of playerDisconnect to end.

So I think it would only confuse users. Of course I can add waiting for async handlers of playerDisconnect to the plugin, but will it be worth it?

**Comment by stanislawkrowicki** [comment]
Running playerDisconnect before restart would be indeed a mediocre idea, but what about running it after restart? 
Probably best disabled by default.
Of course only if altV does not change any player data at all on resource restart, which im not 100% sure.
Resource restart -> playerDisconnect event -> playerConnect event

**Comment by xxshady** [comment]
I think its possible to do it on resource start but then another problems appear: when playerDisconnect is emitted, `alt.Player.all` will still contain "disconnected" player instance on clientside and serverside, also under normal circumstances player instance (baseobject) becomes invalid, and all this stuff should be emulated

**Comment by stanislawkrowicki** [comment]
I think it would be nice to emulate full reconnect, like the one built into altV debug mode, but if you think it's not worth it then it's fine - we can reconnect when really needed ourselves, as lack of emitted playerDisconnect should not be so crucial most of the times.

**Comment by xxshady** [comment]
I will think about it

**Comment by xxshady** [comment]
Okay, I think the time of this issue has come. I will not implement player disconnect emulation to the plugin because it will be too complicated (baseobject invalidation `Error: "baseobject is invalid"`) and not worth it, it is better to implement such option yourself in your own gamemode:
```js
class MyPlayer {
  /** @type {Map<alt.Player, MyPlayer>} */
  static myPlayersByAltPlayer = new Map()

  static onDisconnect = async (myPlayer) => {
    // custom invalidation of the original altv player instance
    MyPlayer.myPlayersByAltPlayer.delete(myPlayer._altPlayer)
    myPlayer._altPlayer = null

    // your custom async logic
    await alt.Utils.wait(1000)

    alt.log('done!')
  }

  _altPlayer
  constructor(altPlayer) {
    this._altPlayer = altPlayer

    MyPlayer.myPlayersByAltPlayer.set(altPlayer, this)
  }
}

alt.on('playerConnect', (player) => {
  new MyPlayer(player)
})

alt.on('playerDisconnect', (altPlayer) => {
  const myPlayer = MyPlayer.myPlayersByAltPlayer.get(altPlayer)
  if (!myPlayer) throw new Error('invalid altPlayer')

  MyPlayer.onDisconnect(myPlayer)
})

// your own dev mode variable or esbuild `define` https://esbuild.github.io/api/#define
if (DEV_MODE) {
  // "disconnecting" all `MyPlayer` players from the server in parallel
  alt.on('resourceStop', async () => {
    const promises = [...MyPlayer.myPlayersByAltPlayer.values()] // all MyPlayer instances
      .map((myPlayer) => MyPlayer.onDisconnect(myPlayer))
    
    await Promise.all(promises)
  })
}
```
